module.exports = {
  flex: { flex: 1 },
  flex0: { flex: 0 },
  flex1: { flex: 0.1 },
  flex2: { flex: 0.2 },
  flex3: { flex: 0.3 },
  flex4: { flex: 0.4 },
  flex5: { flex: 0.5 },
  flex6: { flex: 0.6 },
  flex7: { flex: 0.7 },
  flex8: { flex: 0.8 },
  flex9: { flex: 0.9 },
  noFlex: { flex: -1 },
  contain: { resizeMode: 'contain' },
  cover: { resizeMode: 'cover' },
  stretch: { resizeMode: 'stretch' },
}
